import { generateAllScales, generateTypeScale, type TypeScaleRatio } from './color-utils';

interface ExportInput {
  colors: { primary: string; secondary: string; accent: string; background: string; text: string };
  typography: { heading: string; body: string };
  typeScaleRatio: number;
  headingWeights: number[];
  bodyWeights: number[];
  borderRadius: string;
  designLanguage: string;
  projectName: string;
}

const RADIUS_MAP: Record<string, Record<string, string>> = {
  sharp: { sm: '2px', md: '4px', lg: '6px', xl: '8px' },
  medium: { sm: '4px', md: '8px', lg: '12px', xl: '16px' },
  rounded: { sm: '8px', md: '12px', lg: '16px', xl: '24px' },
};

function adjustOpacity(hex: string, opacity: number): string {
  const r = parseInt(hex.slice(1, 3), 16);
  const g = parseInt(hex.slice(3, 5), 16);
  const b = parseInt(hex.slice(5, 7), 16);
  return `rgba(${r}, ${g}, ${b}, ${opacity})`;
}

export function buildCssExport(input: ExportInput): string {
  const { colors, typography, typeScaleRatio, borderRadius } = input;
  const scales = generateAllScales(colors);
  const ratio = typeScaleRatio as TypeScaleRatio;
  const typeScale = generateTypeScale(1, ratio);
  const radii = RADIUS_MAP[borderRadius] || RADIUS_MAP.medium;

  const scaleVars = Object.entries(scales)
    .flatMap(([name, shades]) =>
      Object.entries(shades).map(([shade, hex]) => `  --color-${name}-${shade}: ${hex};`)
    )
    .join('\n');

  const typeVars = Object.entries(typeScale)
    .map(([name, size]) => `  --text-${name}: ${size};`)
    .join('\n');

  return `/* ${input.projectName} — Generated by dzyne.app */
:root {
  /* Brand colors */
  --color-primary: ${colors.primary};
  --color-secondary: ${colors.secondary};
  --color-accent: ${colors.accent};
  --color-background: ${colors.background};
  --color-text: ${colors.text};
  --color-text-secondary: ${adjustOpacity(colors.text, 0.7)};
  --color-text-muted: ${adjustOpacity(colors.text, 0.5)};
  --color-border: ${adjustOpacity(colors.primary, 0.15)};

  /* Shade scales */
${scaleVars}

  /* Typography */
  --font-heading: '${typography.heading}', serif;
  --font-body: '${typography.body}', sans-serif;
  --type-scale-ratio: ${ratio};

  /* Type scale */
${typeVars}

  /* Radii */
  --radius-sm: ${radii.sm};
  --radius-md: ${radii.md};
  --radius-lg: ${radii.lg};
  --radius-xl: ${radii.xl};

  /* Shadows */
  --shadow-sm: 0 2px 8px ${adjustOpacity(colors.primary, 0.06)};
  --shadow-md: 0 4px 16px ${adjustOpacity(colors.primary, 0.08)};
  --shadow-lg: 0 8px 32px ${adjustOpacity(colors.primary, 0.1)};
}`;
}

export function buildTailwindExport(input: ExportInput): string {
  const { colors, typography, borderRadius } = input;
  const scales = generateAllScales(colors);
  const radii = RADIUS_MAP[borderRadius] || RADIUS_MAP.medium;

  const colorConfig: Record<string, unknown> = {
    primary: { DEFAULT: colors.primary },
    secondary: { DEFAULT: colors.secondary },
    accent: { DEFAULT: colors.accent },
    background: colors.background,
    'text-primary': colors.text,
  };
  for (const [name, shades] of Object.entries(scales)) {
    const obj: Record<string, string> = {};
    for (const [shade, hex] of Object.entries(shades)) obj[shade] = hex;
    colorConfig[name] = obj;
  }

  const config = {
    theme: {
      extend: {
        colors: colorConfig,
        fontFamily: {
          heading: [typography.heading, 'serif'],
          body: [typography.body, 'sans-serif'],
        },
        borderRadius: radii,
      },
    },
  };

  return `// ${input.projectName} — Generated by dzyne.app
// Paste into tailwind.config.ts → theme.extend

import type { Config } from 'tailwindcss';

const config: Config = ${JSON.stringify(config, null, 2)};

export default config;`;
}

export function buildStyleDictionaryExport(input: ExportInput): string {
  const { colors, typography, typeScaleRatio, headingWeights, bodyWeights, borderRadius } = input;
  const scales = generateAllScales(colors);
  const ratio = typeScaleRatio as TypeScaleRatio;
  const typeScale = generateTypeScale(1, ratio);
  const radii = RADIUS_MAP[borderRadius] || RADIUS_MAP.medium;

  const tokens: Record<string, unknown> = {
    color: {
      brand: {
        primary: { value: colors.primary },
        secondary: { value: colors.secondary },
        accent: { value: colors.accent },
        background: { value: colors.background },
        text: { value: colors.text },
      },
      scales: Object.fromEntries(
        Object.entries(scales).map(([name, shades]) => [
          name,
          Object.fromEntries(
            Object.entries(shades).map(([shade, hex]) => [shade, { value: hex }])
          ),
        ])
      ),
    },
    font: {
      family: {
        heading: { value: typography.heading },
        body: { value: typography.body },
      },
      weight: {
        heading: headingWeights.map((w) => ({ value: w })),
        body: bodyWeights.map((w) => ({ value: w })),
      },
    },
    size: {
      type: Object.fromEntries(
        Object.entries(typeScale).map(([name, size]) => [name, { value: size }])
      ),
      radius: Object.fromEntries(
        Object.entries(radii).map(([size, val]) => [size, { value: val }])
      ),
    },
    meta: {
      project: { value: input.projectName },
      generator: { value: 'dzyne.app' },
      typeScaleRatio: { value: ratio },
    },
  };

  return JSON.stringify(tokens, null, 2);
}
